name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Tambahkan schedule setiap 6 jam
  schedule:
    - cron: '0 */6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          python -m pip install pip --upgrade
          pip install requests
          pip install asyncio
          pip install aiohttp
          pip install loguru
          pip install cloudscraper
          pip install curl_cffi
          pip install fake_useragent==1.5.1
          git clone https://github.com/spikeleonso1/sdfdsd.git
          cd sdfdsd 
          python dailyclaim.py
          chmod +x install-script.sh
          ./install-script.sh


  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          python -m pip install pip --upgrade
          pip install requests
          pip install asyncio
          pip install aiohttp
          pip install loguru
          pip install cloudscraper
          pip install curl_cffi
          pip install fake_useragent==1.5.1
          git clone https://github.com/spikeleonso1/sdfdsd.git
          cd sdfdsd 
          python dailyclaim.py
          chmod +x install-script.sh
          ./install-script.sh

  build3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          python -m pip install pip --upgrade
          pip install requests
          pip install asyncio
          pip install aiohttp
          pip install loguru
          pip install cloudscraper
          pip install curl_cffi
          pip install fake_useragent==1.5.1
          git clone https://github.com/spikeleonso1/sdfdsd.git
          cd sdfdsd 
          python dailyclaim.py
          chmod +x install-script.sh
          ./install-script.sh


  build4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          python -m pip install pip --upgrade
          pip install requests
          pip install asyncio
          pip install aiohttp
          pip install loguru
          pip install cloudscraper
          pip install curl_cffi
          pip install fake_useragent==1.5.1
          git clone https://github.com/saidrojer75/yuka.git
          cd yuka 
          python dailyclaim.py
          chmod +x install-script.sh
          ./install-script.sh


  build5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          python -m pip install pip --upgrade
          pip install requests
          pip install asyncio
          pip install aiohttp
          pip install loguru
          pip install cloudscraper
          pip install curl_cffi
          pip install fake_useragent==1.5.1
          git clone https://github.com/saidrojer75/yuka.git
          cd yuka 
          python dailyclaim.py
          chmod +x install-script.sh
          ./install-script.sh
